name: Unpack site
on:
  push:
    paths: ['site.tar.gz']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract homepage source and commit
        run: |
          tar xzf site.tar.gz
          git rm -q site.tar.gz
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Add homepage source"
          git push
